version: "3"
services:
  app:
    image: node:12-alpine
    command: sh -c "npm install --no-save && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  postgresql-data:
