version: "3"
services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  postgresql-data:
